services:
  app:
    image: td.b34r.fr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - database
    environment:
      - TZ=UTC
      - PORT=8082
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=1BK1iOKyOAzh8pTfNdPtrMbdwidsk2MM
      - NODE_ENV=development
      - SESSION_DRIVER=cookie
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=app
      - DISCORD_CLIENT_ID=1294419827372327015
      - DISCORD_CLIENT_SECRET=5DJs_ovDcirFM62mmy1SmGn03qV8hpof
      - DISCORD_BOT_TOKEN=MTI5NDQxOTgyNzM3MjMyNzAxNQ.GsnCsC.PPwAfcwCXAJFdq-5vSBhpk3ow3oKdU1TLKSPIw
      - DISCORD_LSPD=965280713886797824
      - DISCORD_DIVISION=1292138328136880179
  database:
    image: postgres:16-alpine3.19
    ports:
      - 5555:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  psql-data:
